version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - app-network

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=taskmanager.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://taskuser:taskpassword@db:5432/taskmanager
    networks:
      - app-network

  celery:
    build: .
    command: celery -A taskmanager worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=taskmanager.settings
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://taskuser:taskpassword@db:5432/taskmanager
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge